module.exports = {
    drivers : [
        {
            first_name: 'Alan',
            last_name: 'Mehew',
            country_code: '+91',
            phone: "9989898989",
            email: 'khana.khajana@hotspot.com',
            dob: "1992-12-11",
            gender: "Male",
            nationality: "American",
            passport_picture_url:null,
        },
        {
            first_name: 'Seshu',
            last_name: 'Madabushi',
            country_code: '+91',
            phone: "9989898989",
            email: 'tost.host@hotspot.com',
            dob: "1988-08-05",
            gender: "Female",
            nationality: "American",
            passport_picture_url:null,
        },
        {
            first_name: 'Kenneth',
            last_name: 'Marikos',
            country_code: '+91',
            phone: "9989898989",
            email: 'sweets.here@hotspot.com',
            dob: "1998-01-28",
            gender: "Male",
            nationality: "American",
            passport_picture_url:null,
        },
        {
            first_name: 'Ray',
            last_name: 'Kroc',
            country_code: '+91',
            phone: "9989898989",
            email: 'kroc.foods@hotspot.com',
            dob: "1978-05-09",
            gender: "Female",
            nationality: "American",
            passport_picture_url:null,
        },
        {
            first_name: 'Steve',
            last_name: 'Ells',
            country_code: '+91',
            phone: "9989898989",
            email: 'steve.kichen@hotspot.com',
            dob: "1987-07-16",
            gender: "Male",
            nationality: "American",
            passport_picture_url:null,
        },
    ],
}