module.exports = {
    drivers : [
        {
            first_name: 'Alan',
            last_name: 'Mehew',
            country_code: '+91',
            phone: 9989898989,
            email: 'khana.khajana@hotspot.com',
            dob: "1992-12-11",
            gender: "Male",
            nationality: "American",
            passport_picture_url:"https://hotspot-customer-profile-picture1.s3.amazonaws.com/driver_1615383046905.jfif",
        },
        {
            first_name: 'Seshu',
            last_name: 'Madabushi',
            country_code: '+91',
            phone: 9989898989,
            email: 'tost.host@hotspot.com',
            dob: "1988-08-05",
            gender: "Female",
            nationality: "American",
            passport_picture_url:"https://hotspot-customer-profile-picture1.s3.amazonaws.com/driver_1615383014605.jfif",
        },
        {
            first_name: 'Kenneth',
            last_name: 'Marikos',
            country_code: '+91',
            phone: 9989898989,
            email: 'sweets.here@hotspot.com',
            dob: "1998-01-28",
            gender: "Male",
            nationality: "American",
            passport_picture_url:"https://hotspot-customer-profile-picture1.s3.amazonaws.com/driver_1615383069242.jfif",
        },
        {
            first_name: 'Ray',
            last_name: 'Kroc',
            country_code: '+91',
            phone: 9989898989,
            email: 'kroc.foods@hotspot.com',
            dob: "1978-05-09",
            gender: "Female",
            nationality: "American",
            passport_picture_url:"https://hotspot-customer-profile-picture1.s3.amazonaws.com/driver_1615383099244.jfif",
        },
        {
            first_name: 'Steve',
            last_name: 'Ells',
            country_code: '+91',
            phone: 9989898989,
            email: 'steve.kichen@hotspot.com',
            dob: "1987-07-16",
            gender: "Male",
            nationality: "American",
            passport_picture_url:"https://hotspot-customer-profile-picture1.s3.amazonaws.com/driver_1615383123839.jfif",
        },
    ],

    driver_addresses : [
        {
            address_line1: '"Ghaziabad, Uttar Pradesh, 201001, India"',
            street: 'pahli gali',
            city: 'Ghaziabad',
            state: "Uttar Pradesh",
            postal_code: '201301',
        },
        {
            address_line1: "Naugarh, Siddharth Nagar, Uttar Pradesh, 272203, India",
            street: 'Siddharth',
            city: 'Naugarh',
            state: "Uttar Pradesh",
            postal_code: '272203',
        },
        {
            address_line1: "Upper Shankar Vihar, Shankar Vihar, Delhi Cantonment",
            street: 'Shankar Vihar',
            city: 'New Delhi',
            state: "Delhi",
            postal_code: '110010',
        },
        {
            address_line1: "Vasant Vihar Tehsil, Delhi 122010",
            street: 'Vasant Vihar',
            city: 'New Delhi',
            state: "Delhi",
            postal_code: '122010',
        },
        {
            address_line1: "Dr. Rajendra Prasad Marg, Ghaziabad, Uttar Pradesh, 201004",
            street: 'Rajendra Prasad Marg',
            city: 'Ghaziabad',
            state: "Uttar Pradesh",
            postal_code: '201004',
        },
    ],

    driver_vehicle_details: [
        {
            vehicle_type: "Truck",
            image_url: "https://hotspot-customer-profile-picture1.s3.amazonaws.com/driver_vehicle_1615437036506.jfif",
            plate_number: "ERS-8579",
            vehicle_model: "AMC Hornet",
            license_number: "S123-456-57-901-6",
            license_image_url: "https://hotspot-customer-profile-picture1.s3.amazonaws.com/driver_license_1615437985282.jfif",
            insurance_number: "225-4538-7852",
            insurance_image_url:"https://hotspot-customer-profile-picture1.s3.amazonaws.com/driver_insurance_1615438510969.png",
        },
        {
            vehicle_type: "Van",
            image_url: "https://hotspot-customer-profile-picture1.s3.amazonaws.com/driver_vehicle_1615437093715.jfif",
            plate_number: "JKM-4855",
            vehicle_model: "Austin Maestro",
            license_number: "S453-654-87-109-0",
            license_image_url: "https://hotspot-customer-profile-picture1.s3.amazonaws.com/driver_license_1615437938874.jfif",
            insurance_number: "826-4527-7521",
            insurance_image_url:"https://hotspot-customer-profile-picture1.s3.amazonaws.com/driver_insurance_1615438537267.jfif",
        },
        {
            vehicle_type: "Bike",
            image_url: "https://hotspot-customer-profile-picture1.s3.amazonaws.com/driver_vehicle_1615437142617.jfif",
            plate_number: "FGY-5597",
            vehicle_model: "Dodge Viper",
            license_number: "S543-158-57-349-5",
            license_image_url: "https://hotspot-customer-profile-picture1.s3.amazonaws.com/driver_license_1615438011063.jfif",
            insurance_number: "542-1235-7895",
            insurance_image_url:"https://hotspot-customer-profile-picture1.s3.amazonaws.com/driver_insurance_1615438563063.png",
        },
        {
            vehicle_type: "Truck",
            image_url: "https://hotspot-customer-profile-picture1.s3.amazonaws.com/driver_vehicle_1615437067559.jfif",
            plate_number: "VCF-6879",
            vehicle_model: "Cadillac ELR",
            license_number: "S582-889-12-287-8",
            license_image_url: "https://hotspot-customer-profile-picture1.s3.amazonaws.com/driver_license_1615438039156.jfif",
            insurance_number: "258-1593-3698",
            insurance_image_url:"https://hotspot-customer-profile-picture1.s3.amazonaws.com/driver_insurance_1615438585678.jfif",
        },
        {
            vehicle_type: "Van",
            image_url: "https://hotspot-customer-profile-picture1.s3.amazonaws.com/driver_vehicle_1615437116208.jfif",
            plate_number: "UYR-1573",
            vehicle_model: "Crosley",
            license_number: "S987-258-11-253-3",
            license_image_url: "https://hotspot-customer-profile-picture1.s3.amazonaws.com/driver_license_1615438078088.jfif",
            insurance_number: "148-2561-4528",
            insurance_image_url:"https://hotspot-customer-profile-picture1.s3.amazonaws.com/driver_insurance_1615438610371.jfif",
        }
    ],

}